// COMMON
export const LOADING = "LOADING";
export const STOP_LOADING = "STOP_LOADING";

// LOGIN
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILED = "REGISTER_FAILED";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILED = "LOGOUT_FAILED";
export const SET_USERNAME = "SET_USERNAME";

// RUNS
export const FETCH_LIST_SUCCESS = "FETCH_LIST_SUCCESS";
export const FETCH_LIST_FAILED = "FETCH_LIST_FAILED";
export const ADD_RUN_SUCCESS = "ADD_RUN_SUCCESS";
export const ADD_RUN_FAILED = "ADD_RUN_FAILED";
export const REMOVE_RUN_SUCCESS = "REMOVE_RUN_SUCCESS";
export const REMOVE_RUN_FAILED = "REMOVE_RUN_FAILED";
export const EDIT_RUN_SUCCESS = "EDIT_RUN_SUCCESS";
export const EDIT_RUN_FAILED = "EDIT_RUN_FAILED";